In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv("/content/covid_toy.csv")
df.head(5)

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
X = df.drop('has_covid', axis = 1)
y = df['has_covid']

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42)

In [7]:
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers=[
    ('imput',SimpleImputer(),['fever']),
    ('ordinal',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('onehot',OneHotEncoder(sparse_output =False,drop='first'),['gender','city'])
],remainder='passthrough')

In [12]:
X_train_transformed = transformer.fit_transform(X_train)
X_test_transformed = transformer.transform(X_test)

In [13]:
# Get column names
columns = transformer.get_feature_names_out()

# Convert to DataFrame
X_train_df = pd.DataFrame(X_train_transformed, columns=columns)
X_test_df = pd.DataFrame(X_test_transformed, columns=columns)

In [15]:
X_train_df.head(5)

,imput__fever,ordinal__cough,onehot__gender_Male,onehot__city_Delhi,onehot__city_Kolkata,onehot__city_Mumbai,remainder__age
0,101.0,0.0,0.0,0.0,0.0,1.0,81.0
1,100.0,0.0,0.0,0.0,1.0,0.0,5.0
2,100.0,0.0,0.0,0.0,1.0,0.0,19.0
3,100.0,0.0,1.0,1.0,0.0,0.0,27.0
4,103.0,0.0,0.0,1.0,0.0,0.0,73.0