In [1]:
import numpy as np  
import pandas as pd  
import matplotlib.pyplot as plt  
import seaborn as sns

In [2]:
df = pd.read_csv("heart.csv")
df.sample(5)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
483,35,1,1,122,192,0,1,174,0,0.0,2,0,2,1
604,47,1,2,130,253,0,1,179,0,0.0,2,0,2,1
965,76,0,2,140,197,0,2,116,0,1.1,1,0,2,1
762,56,1,1,130,221,0,0,163,0,0.0,2,0,3,1
505,44,0,2,118,242,0,1,149,0,0.3,1,1,2,1

Categorical Columns  
sex  
cp    
fbs  
restecg  
exang
ca  
thal

In [4]:
df['cp'].value_counts()

cp
0    497
2    284
1    167
3     77
Name: count, dtype: int64

In [5]:
df['thal'].value_counts()

thal
2    544
3    410
1     64
0      7
Name: count, dtype: int64

In [6]:
X = df.drop('target',axis = 1)
y = df['target']

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42)

In [8]:
from sklearn.preprocessing import OneHotEncoder
cp_ohe = OneHotEncoder(sparse_output=False, drop='first').set_output(transform='pandas')
cp_ohe.fit(X_train[['cp']])
cp_df = cp_ohe.transform(X_train[['cp']])
X_train = pd.concat([X_train,cp_df],axis =1)
cp_df = cp_ohe.transform(X_test[['cp']])
X_test = pd.concat([X_test,cp_df],axis =1)

In [9]:
X_train.head(5)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,cp_1,cp_2,cp_3
835,49,1,2,118,149,0,0,126,0,0.8,2,3,2,0.0,1.0,0.0
137,64,0,0,180,325,0,1,154,1,0.0,2,0,2,0.0,0.0,0.0
534,54,0,2,108,267,0,0,167,0,0.0,2,0,2,0.0,1.0,0.0
495,59,1,0,135,234,0,1,161,0,0.5,1,0,3,0.0,0.0,0.0
244,51,1,2,125,245,1,0,166,0,2.4,1,0,2,0.0,1.0,0.0

In [10]:
thal_ohe = OneHotEncoder(sparse_output=False, drop='first').set_output(transform='pandas')
thal_ohe.fit(X_train[['thal']])
thal_df = thal_ohe.transform(X_train[['thal']])
X_train = pd.concat([X_train,thal_df],axis =1)
thal_df = thal_ohe.transform(X_test[['thal']])
X_test = pd.concat([X_test,thal_df],axis =1)

In [11]:
X_train.head(5)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,cp_1,cp_2,cp_3,thal_1,thal_2,thal_3
835,49,1,2,118,149,0,0,126,0,0.8,2,3,2,0.0,1.0,0.0,0.0,1.0,0.0
137,64,0,0,180,325,0,1,154,1,0.0,2,0,2,0.0,0.0,0.0,0.0,1.0,0.0
534,54,0,2,108,267,0,0,167,0,0.0,2,0,2,0.0,1.0,0.0,0.0,1.0,0.0
495,59,1,0,135,234,0,1,161,0,0.5,1,0,3,0.0,0.0,0.0,0.0,0.0,1.0
244,51,1,2,125,245,1,0,166,0,2.4,1,0,2,0.0,1.0,0.0,0.0,1.0,0.0

In [12]:
X_train.drop(['cp','thal'], axis = 1, inplace = True)

In [13]:
X_train.head(5)

,age,sex,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,cp_1,cp_2,cp_3,thal_1,thal_2,thal_3
835,49,1,118,149,0,0,126,0,0.8,2,3,0.0,1.0,0.0,0.0,1.0,0.0
137,64,0,180,325,0,1,154,1,0.0,2,0,0.0,0.0,0.0,0.0,1.0,0.0
534,54,0,108,267,0,0,167,0,0.0,2,0,0.0,1.0,0.0,0.0,1.0,0.0
495,59,1,135,234,0,1,161,0,0.5,1,0,0.0,0.0,0.0,0.0,0.0,1.0
244,51,1,125,245,1,0,166,0,2.4,1,0,0.0,1.0,0.0,0.0,1.0,0.0

In [ ]:
thal_ohe = OneHotEncoder(sparse_output=False, drop='first').set_output(transform='pandas')
thal_ohe.fit(X_train[['thal']])
thal_df = thal_ohe.transform(X_train[['thal']])
X_train = pd.concat([X_train,thal_df],axis =1)
thal_df = thal_ohe.transform(X_test[['thal']])
X_test = pd.concat([X_test,thal_df],axis =1)