In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("/content/cars.csv")
df.head(5)

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [3]:
X =df.drop("selling_price", axis = 1)
y = df['selling_price']

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42)

In [5]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])
X_test_new = ohe.transform(X_test[['fuel','owner']])

In [6]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Tata', 2560, 0, ..., 0, 0, 0],
       ['Honda', 80000, 0, ..., 1, 0, 0],
       ['Hyundai', 150000, 1, ..., 0, 0, 0],
       ...,
       ['Hyundai', 35000, 0, ..., 0, 0, 0],
       ['Maruti', 27000, 1, ..., 0, 0, 0],
       ['Maruti', 70000, 0, ..., 1, 0, 0]], dtype=object)

In [7]:
X_train_new = pd.DataFrame(
    X_train_new,
    columns=ohe.get_feature_names_out()
)

X_test_new = pd.DataFrame(
    X_test_new,
    columns=ohe.get_feature_names_out())

In [8]:
X_train_final = pd.concat([X_train.drop(['fuel', 'owner'], axis=1), X_train_new], axis=1)
X_test_final  = pd.concat([X_test.drop(['fuel', 'owner'], axis=1), X_test_new], axis=1)

In [9]:
X_train_final.head(5)

,brand,km_driven,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
6518,Tata,2560.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6144,Honda,80000.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
6381,Hyundai,150000.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
438,Maruti,120000.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5939,Maruti,25000.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
df['brand'].nunique()
limit = 100
counts = df['brand'].value_counts()
replaces = counts[counts <= limit].index
pd.get_dummies(df['brand'].replace(replaces, 'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
2563,False,False,False,False,False,False,False,False,False,True,False,False,False
2570,False,False,False,False,False,True,False,False,False,False,False,False,False
7088,False,False,False,False,False,False,True,False,False,False,False,False,False
3318,False,False,False,False,False,False,False,False,False,True,False,False,False
5824,False,False,False,False,False,False,False,False,False,False,False,True,False

In [18]:
replaces = counts[counts <= limit].index

In [21]:
replaces.nunique()

20