In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df= pd.read_csv("/content/customer.csv")

In [ ]:
df.head(5)

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [ ]:
df = df.iloc[:,2:]

In [ ]:
df.head(5)

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [ ]:
X= df.drop('purchased', axis =1)
y = df['purchased']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42)

In [ ]:
X_train['education'].value_counts()

education
School    14
PG        14
UG        12
Name: count, dtype: int64

In [ ]:
X_train['review'].value_counts()

review
Good       16
Poor       13
Average    11
Name: count, dtype: int64

In [ ]:

from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories = [["Poor","Average","Good"], ['School', 'UG', 'PG']] )
oe.fit(X_train)
X_train_scaled = oe.transform(X_train)
X_test_scaled = oe.transform(X_test)

In [ ]:
X_train_scaled = pd.DataFrame(X_train_scaled, columns = X_train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns = X_test.columns)

In [ ]:
X_train_scaled.head(5)

   review  education
0     0.0        0.0
1     1.0        1.0
2     1.0        2.0
3     1.0        1.0
4     2.0        2.0

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)
y_train_scaled = le.transform(y_train)
y_test_scaled = le.transform(y_test)

In [ ]:
y_train_scaled = pd.DataFrame(y_train_scaled, columns = ['purchased'])
y_test_scaled = pd.DataFrame(y_test_scaled, columns = ['purchased'])

In [ ]:
y_train_scaled.head(5)

   purchased
0          0
1          0
2          1
3          0
4          0